version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: quickly_pick_dev
      POSTGRES_USER: quicklypick
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quicklypick"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: